[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
